# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/date-helper',
                'doc_host': 'https://tw13023.github.io',
                'git_url': 'https://github.com/tw13023/date-helper',
                'lib_path': 'date_helper'},
  'syms': {'date_helper.core': {'date_helper.core.days_between': ('core.html#days_between', 'date_helper/core.py')}}}
